### ISSUE TITLE
Add Hint Model

### ISSUE THREAD

**Issue by iccelou91** [ba-sing-sec/GoatCTF#32]
The Hint model will have the following fields:
created_date - DateTimeField
challenge - Challenge
content - TextField

**Comment by ianonavy** [comment]
Why not just modify the description?

**Comment by iccelou91** [comment]
Adding a new model would allow notifications to pop up when new hints are added. It could also allow other features like making displaying hints optional.

**Comment by ianonavy** [comment]
I mentioned this to Deemer, and he also mentioned that you could pre-populate hints and have them auto-display at a certain time.
